config/routes.rb
DataEngineering::Application.routes.draw do
  
  devise_for :users
  get "home/index"
   
  match '/upload' => 'home#upload', :as => :upload, :via => [:post]
  match '/download' => 'home#download', :as => :download, :via => [:get]

  root 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

	validates :price, presence: true 
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base

	validates :name, presence: true 
	validates :address, presence: true 

end

app/models/purchaser.rb
class Purchaser < ActiveRecord::Base
end

app/models/sale.rb
class Sale < ActiveRecord::Base

	belongs_to :item
	belongs_to :merchant
	belongs_to :purchaser
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@gross_revenue = params[:gross_revenue]
	end

    
    # Upload the .tab file
	def upload
		if params[:file]
			uploader = DataEngineering::Uploader.new(params[:file].path)
			@gross_revenue = uploader.perform
			flash[:success] = 'Successfully Uploaded!'
		else
			flash[:warning] = 'No File selected!'
		end
		redirect_to root_url(gross_revenue: @gross_revenue) 
	end
    
    #Download the .tab file
	def download
		send_file "#{Rails.root}/public/dummy_data.tab"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def formatted(sale)
		str = ' '
		str << sale.purchase_count.to_s
		str << ' * '
		str << sale.item.price.to_s
		str
	end

	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_pricing_table.html.haml
%ul.pricing-table
  %li.title Calculated Total Gross Revenue
  %li.description This is based on the Sales
  - Sale.all.each do |sale|
    %li.bullet-item
      %h6
        = formatted(sale)
  %li.price 
    = number_to_currency(gross_revenue)
  %li.cta-button
    
    

app/views/home/index.html.haml
= form_tag upload_url ,multipart: true do
  %fieldset
    %legend
      Upload 
    %label
    = file_field_tag :file

    .small-3.small-centered.columns
      = submit_tag 'Submit', class: 'button small'

    %span.label.secondary
      = t(:note)

    %span.right
      %p
        Don't have file to upload? 
        = link_to 'Download',download_url
- if @gross_revenue
  = scroll_reveal animation: 'enter right after 1s' do 
    = render partial: 'pricing_table',locals: {gross_revenue: @gross_revenue}

app/views/layouts/_ankit_social_links.html.haml
%ul.right
  %li.active
    = link_to 'https://github.com/ankit8898',target: '_blank' do 
      = content_tag(:i,nil,class: 'fa fa-github-square')
  %li.active
    = link_to 'https://twitter.com/ankit8898',target: '_blank' do 
      = content_tag(:i,nil,class: 'fa fa-twitter')
  %li.active
    = link_to 'https://linkedin.com/pub/ankit-gupta/25/205/254/', target: '_blank' do 
      = content_tag(:i,nil,class: 'fa fa-linkedin-square')
  %li.active
    = link_to 'http://stackoverflow.com/users/662425/ankitg', target: '_blank' do 
      = content_tag(:i,nil,class: 'fa fa-stack-overflow')
  %li.active
    = link_to 'http://instagram.com/ag_instagraphy', target: '_blank' do 
      = content_tag(:i,nil,class: 'fa fa-instagram')
  - if user_signed_in?
    %li.has-dropdown
      = link_to "Welcome, #{current_user.email}"
      %ul.dropdown
        %li
          = link_to 'Sign Out',destroy_user_session_path, method: :delete

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - klass = name.eql?(:success) || name.eql?(:notice) ? 'success' : name
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "alert-box #{klass}"
    

app/views/layouts/_top_nav.html.haml
%nav.top-bar{"data-topbar" => ""}
  %ul.title-area
    %li.name
      %h1
        = link_to root_url do 
          = content_tag(:i,' Data Engineering',class: 'fa fa-cog')
    %li.toggle-topbar.menu-icon
      %a{href: "#"} Menu
  %section.top-bar-section
    / Right Nav Section
    = render partial: 'layouts/ankit_social_links'
     

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title
      Data Engineering
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render partial: 'layouts/top_nav'
    .row
      = render partial: 'layouts/messages'
      .small-6.large-2.columns
        &nbsp;
      .small-6.large-8.columns
        = yield
      .small-12.large-2.columns
        &nbsp;
    = javascript_include_tag "application"
    = content_for(:js_on_page)